### ISSUE TITLE
mantab working!

### ISSUE THREAD

**Issue by myfacefx** [namdevel/gopay-api#1]
can u add other api features, like buy pulsa,food,or digital product

**Comment by namdevel** [comment]
iya nanti kalo senggang, soalnya ini api dibuat tujuan nya untuk cek mutasi aja, buat nerima payment via gopay di web.
kalo mau buy pulsa dll, enaknya lewat aplikasinya lgsung

**Comment by myfacefx** [comment]
ok,sebenere saya cari trx beli emas nya. ternyata ada juga dgn gopay gojek ke pluang. cuman kudu tracking order flownya. mungkin mas bro,bisa bantu. link order emas nya disini https://goinvestasi.pluang.com/. aku liat sih, mode sebelum login,minta akses ke akun gojek dgn otp. baru dapet sessionnya lalu bisa order emasnya

**Comment by namdevel** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/62225978/81558576-20190e80-93b8-11ea-9671-b27bb0e1b702.png)
![Screenshot_33](https://user-images.githubusercontent.com/62225978/81558686-52c30700-93b8-11ea-821f-62bb20eb8dec.png)

**Comment by namdevel** [comment]
![Screenshot_34](https://user-images.githubusercontent.com/62225978/81558830-9289ee80-93b8-11ea-86bf-9db9bab0e220.png)
![Screenshot_35](https://user-images.githubusercontent.com/62225978/81558834-9453b200-93b8-11ea-89aa-41d583d36525.png)

**Comment by myfacefx** [comment]
ada kontak skype mas? bisa emailin ya ke dnang99@gmail.com
