### ISSUE TITLE
login attempts multiple phone numbers

### ISSUE THREAD

**Issue by gyugie** [namdevel/gopay-api#10]
https://goid.gojekapi.com/goid/login/request goid:error:ratelimited:device => For your safety, we keep a limit on back-to-back login attempts from multiple phone numbers.

klo kena limit seperti ini gmn ya gan?

**Comment by namdevel** [comment]
ganti aja id nya

```
$this->sessionId = 'A78354AB-9578-4FF5-B899-4BA6BA16488E'; // generated from self::uuidv4();
$this->uniqueId  = 'A23194EB-8C6F-45B7-8A80-2606BA847DD8'; // generated from self::uuidv4();
```

**Comment by gyugie** [comment]
> ganti aja id nya
> 
> ```
> $this->sessionId = 'A78354AB-9578-4FF5-B899-4BA6BA16488E'; // generated from self::uuidv4();
> $this->uniqueId  = 'A23194EB-8C6F-45B7-8A80-2606BA847DD8'; // generated from self::uuidv4();
> ```

okeee terima kasih gan works

**Comment by cakracomp** [comment]
https://github.com/namdevel/gopay-api/issues/10#issuecomment-919816802

gan ini errornya masih sama per 2 agustus 22

**Comment by cakracomp** [comment]
$this->sessionId = 'A78354AB-9578-4FF5-B899-4BA6BA16488E'; // generated from self::uuidv4();
$this->uniqueId  = 'A23194EB-8C6F-45B7-8A80-2606BA847DD8'; // generated from self::uuidv4();

ini errornya masih sama gan per 2 agustus 2022

**Comment by namdevel** [comment]
ganti dulu gan sama yg baru , kalo gk di ganti  ya error
