### ISSUE TITLE
send otp failed

### ISSUE THREAD

**Issue by myfrizqi** [namdevel/gopay-api#12]
berikut pesan yang muncul:
Please update to the latest official app version and try to login again

**Comment by bocah-tua-nakal** [comment]
Kemarin sempat error tapi saya cek sekarang sih aman

> berikut pesan yang muncul: Please update to the latest official app version and try to login again

**Comment by myfrizqi** [comment]
masih tetap error mas barusan saya coba lagi

**Comment by namdevel** [comment]
saya tes kode lama masi bisa, coba di tes ulang sudah saya update versi nya

**Comment by myfrizqi** [comment]
sudah bisa sekarang mas. terima kasih mas @namdevel @bocah-tua-nakal
