### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by I-CoderTeam** [namdevel/gopay-api#13]
kenapa pas login muncul spt ini yaa??

{"data":null,"success":false,"errors":[{"code":"goid:error:unauthorized","message":"Please update to the latest official app version and try to login again.","message_title":"Unauthorized"}]}

**Comment by namdevel** [comment]
Pake versi brp? 
terbaru versi [v1.2](https://github.com/namdevel/gopay-api/releases/tag/1.2)

**Comment by toni-ismail** [comment]
Sama gan, baru muncul nh karena ada update gojek v 38.1
Step : 
1. Pas dpt token
2. Login
3.  Muncul pesan error sbb
{"data":null,"success":false,"errors":[{"code":"goid:error:unauthorized","message":"Please update to the latest official app version and try to login again.","message_title":"Unauthorized"}]}

Mohon updatenya gan.
