### ISSUE TITLE
2FA code require at the time send request otp-token & otp-code

### ISSUE THREAD

**Issue by TruongNgocTai** [namdevel/gopay-api#14]
Hello, 
after I get otp-token from responed json and otp-code from sms, Gojek app request input 2FA code from app.
Please help me!
![image](https://user-images.githubusercontent.com/31515410/159118008-4a6a7b91-f34c-4116-bc59-0582b55401e7.png)

**Comment by fakkw** [comment]
Please logout first from the device you are using
