### ISSUE TITLE
Nomor Selalu terblokir semenjak konek dengan api unofficial ini

### ISSUE THREAD

**Issue by cvkjm** [namdevel/gopay-api#16]
Maaf mas mau nanya, saya nemu kasus untuk nomor2 yang nempel dengan API unofficial ini apabila sudah mencapai transaksi masuk diatas 1.5 juta kenapa selalu terblokir ya? Pesan terblokirnya masalah security akses

**Comment by cvkjm** [comment]
ini salah 1 contoh nya koding mutasi saya

<?php
error_reporting(0);
header('Content-Type: application/json');
set_time_limit(0);

$urutan=$_GET['urutan'];

if($urutan=="GOPAY1"){
 require('../src/GojekPay.php');
}
if($urutan=="GOPAY2"){
 require('../src/GojekPay2.php');
}
if($urutan=="GOPAY3"){
 require('../src/GojekPay3.php');
}
if($urutan=="GOPAY4"){
 require('../src/GojekPay4.php');
}
if($urutan=="GOPAY5"){
 require('../src/GojekPay5.php');
}
if($urutan=="GOPAY6"){
 require('../src/GojekPay6.php');
}
if($urutan=="GOPAY7"){
 require('../src/GojekPay7.php');
}
if($urutan=="GOPAY8"){
 require('../src/GojekPay8.php');
}
if($urutan=="GOPAY9"){
 require('../src/GojekPay9.php');
}
if($urutan=="GOPAY10"){
 require('../src/GojekPay10.php');
}
if($urutan=="GOPAY11"){
 require('../src/GojekPay11.php');
}
if($urutan=="GOPAY12"){
 require('../src/GojekPay12.php');
}
if($urutan=="GOPAY13"){
 require('../src/GojekPay13.php');
}
if($urutan=="GOPAY14"){
 require('../src/GojekPay14.php');
}
if($urutan=="GOPAY15"){
 require('../src/GojekPay15.php');
}

include '../../koneksi.php';
use Namdevel\GojekPay;
$nohp=$_GET['nohp'];
$q1x = mysqli_query($koneksi,"select * from gojek where gojek='$nohp' order by id DESC limit 1  ");
$r1x=mysqli_fetch_array($q1x);
$token = $r1x['app'];
if($token!=""){
$app = new GojekPay($token);


$data=$app->getTransactionHistory();
/** 
@ step 2
return @type json contain <access_token> 
*/
$result222a = json_decode($data,true);

 $arr = array();
  $arr["data"] = array();
for($x=0;$x<20;$x++){
	$transactionid=$result222a["data"]["success"][$x]["transaction_ref"];
	$description=$result222a["data"]["success"][$x]["description"];
	$description=str_replace("'", " ", $description);
	$value=$result222a["data"]["success"][$x]["amount"]["value"];
	$jenis=$result222a["data"]["success"][$x]["type"];
   $data = array(
            'transactionid' => $transactionid,
            'description' => $description,
            'value' => $value,
			'jenis' => $jenis,
			
        );
        array_push($arr["data"], $data);
}

echo json_encode($arr);
}
?>

**Comment by namdevel** [comment]
device ID harus unique tiuap nomor HP, jangan sering rubah2 , resikonya kena block
dan coba cara ngoding nya lebih terstruktur lagi
