### ISSUE TITLE
tuluung bang

### ISSUE THREAD

**Issue by cakracomp** [namdevel/gopay-api#17]
login request muncul ini bang
![image](https://user-images.githubusercontent.com/37916643/182283408-ec4893ea-f96b-4ead-98d0-bb33241de8f0.png)

**Comment by namdevel** [comment]
ganti device ID 
bagian itu di ganti

[uuidv4](https://www.uuidgenerator.net/version4)

$this->sessionId = 'A78354AB-9578-4FF5-B899-4BA6BA16488E'; // generated from self::uuidv4();
$this->uniqueId  = 'A23194EB-8C6F-45B7-8A80-2606BA847DD8'; // generated from self::uuidv4();

**Comment by cakracomp** [comment]
mantul bang.. ntar cair gw traktor bang..wkwk

**Comment by cakracomp** [comment]
bang 1 lagi. klo logout syntaxnya gimana ya?
