### ISSUE TITLE
Can't send getAuthToken

### ISSUE THREAD

**Issue by DitoBaskaran** [namdevel/gopay-api#2]
{"data":null,"success":false,"errors":[{"code":"goid:error:internal","message":"Something went wrong","message_title":"Internal error"}]}

Why???

**Comment by namdevel** [comment]
![Screenshot_24](https://user-images.githubusercontent.com/62225978/94369643-5233ce80-0115-11eb-9e81-fe22494273ec.png)

i'm trying still working fine

**Comment by namdevel** [comment]
there is 2 step
1.  echo $gopay->loginRequest('<phoneNumber>'); 
2. echo $gopay->getAuthToken('<otpToken>', '<otpCode>');

separate that code from getAuthToken.php , do not run it both
