### ISSUE TITLE
LOGIN

### ISSUE THREAD

**Issue by LannDigital018** [namdevel/gopay-api#20]
SAYA KAN PASANG DI HOSTING YA KAN, INI GA BISA MULTI LOGIN SETIAP USER YA GAN ?

**Comment by namdevel** [comment]
gabisa, kebijakan dari gojeknya jika login ke perangkat baru, perangkat lama bakal logout

**Comment by mhmdlanna** [comment]
Boleh send kontak tele ga bang? mau diskusi

**Comment by LannDigital018** [comment]
bang, ini saya login tapi ada bacaan error kek gini "Try logging in after 12 hours" Padahal w tidak pernah login ke Gojek di nomer yang gw mau login nin.
