### ISSUE TITLE
isGojek not working

### ISSUE THREAD

**Issue by g00m00nry0ng** [namdevel/gopay-api#3]
function isGojek memberikan response berikut

{"success":false,"data":null,"errors":[{"code":"GoPay-105","message_title":"Wallet not found","message":"We couldn't find your wallet.","message_severity":"error"}]}

padahal baik nomer pengirim dan penerima adalah nomor Gojek yg valid.

**Comment by namdevel** [comment]
masukkan nomor HP lengkap disertai dengan +62

**Comment by g00m00nry0ng** [comment]
Thx a million!
