### ISSUE TITLE
Transfer Bank

### ISSUE THREAD

**Issue by Arlchoose** [namdevel/gopay-api#34]
Gimana ya cara agar transfer bank nya mengikuti dari aplikasi Gopay dan bukan Gojek agar tidak terkena fee 2500? Help help

**Comment by Arlchoose** [comment]
Jadi tf itu ngikutin apk gopay bukan dari gojek, soalnya gopay free tf 100x perbulan. Soalnya sempet intip dikit juga endpoint nya sama aja

**Comment by kusanagi1337** [comment]
belum nemu, soalnya coba bypas ssl pinning apk gopay itu gak kebaca paramnya

**Comment by Arlchoose** [comment]
Done sudah teratasi
