### ISSUE TITLE
Gagal Transfer Gopay

### ISSUE THREAD

**Issue by dutta07** [namdevel/gopay-api#7]
![image](https://user-images.githubusercontent.com/60208449/127864424-ddda97dd-79ac-40d2-b3ed-eb113eefa06d.png)

tiap tf ke gopay selalu beigut, sudah dicoba pake akun yang berbeda tapi ttp error

Terimakasih, mohon dicek

**Comment by reactmore** [comment]
Bukan Akun nya format nya berubah mungkin sudah bukan payee => array ( 'id' => QRID)

**Comment by dutta07** [comment]
> Bukan Akun nya format nya berubah mungkin sudah bukan payee => array ( 'id' => QRID)

iyaa bisa jadi, cm saya kurang tau persis makanya open issue

**Comment by namdevel** [comment]
masih error ?

**Comment by dutta07** [comment]
> masih error ?

terakhir kemaren masih error

**Comment by namdevel** [comment]
setelah saya test masih bisa kok, pastikan no HP tujuan di awali +62

**Comment by dutta07** [comment]
oke nnti ku cek lagi

**Comment by reactmore** [comment]
> setelah saya test masih bisa kok, pastikan no HP tujuan di awali +62

Gimana om masih kena malformat

```php
$gopay = new Main($sessions['access_token']);
$transfer = $gopay->transferGopay('+6283819294323', '10200', 'xxxx');

echo '<pre>';
var_dump($transfer);
echo '<pre>';
```

Response 
string(263) "{
  "success": false,
  "error": {
    "code": "310",
    "description": "Malformed data"
  },
  "errors": [
    {
      "code": "GoPay-310",
      "message": "Malformed data",
      "message_title": "Malformed data",
      "message_severity": "error"
    }
  ]
}"

**Comment by namdevel** [comment]
nominal (amount) jangan pake tanda petik

![res](https://user-images.githubusercontent.com/62225978/128790852-849db868-d6d2-4659-9e62-1c3e0a9053fc.png)

**Comment by dutta07** [comment]
> nominal (amount) jangan pake tanda petik
> 
> ![res](https://user-images.githubusercontent.com/62225978/128790852-849db868-d6d2-4659-9e62-1c3e0a9053fc.png)

oke sudah solved.. ammountnya harus pake integer..

**Comment by g00m00nry0ng** [comment]
ok, bener Gan. problemnya di amount. setelah saya rubah $amount menjadi (int)$amount sudah fix sekarang. Thx ya scriptnya jadi sbb:

    public function transferGopay($qr_id,$amount, $pin)
    {
        $this->pin = $pin;
        $payload = array(
            'amount' => array(
                'currency' => 'IDR',
                'value' => (int)$amount
            ),
            'description' => 'nama pengiriman',
            'metadata' => array(
                'post_visibility' => 'NO_SOCIAL',
                'theme_id' => 'THEME_CLASSIC'
            ),
            'payee' => array(
                'id' => $qr_id,
                'id_type' => 'GOPAY_QR_ID'
            )
        );
        echo self::Request(self::API_CUSTOMER . '/v1/funds/transfer', $payload, true);
    }
