### ISSUE TITLE
Endpoint API

### ISSUE THREAD

**Issue by izzatzr** [namdevel/gopay-api#8]
Boleh tau endpoint API , parameter , dlsb ini didapatkan darimana ya ?

**Comment by namdevel** [comment]
dari aplikasinya lgsung pak bisa dengan decompile APK nya, atau bisa dari capture http request nya

**Comment by izzatzr** [comment]
> dari aplikasinya lgsung pak bisa dengan decompile APK nya, atau bisa dari capture http request nya

ok thanks infonyaa
